In [ ]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")
# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).

# Your code for Task 1 here:
arr1_1 = np.arange(100)
arr1_2 = np.ones((3, 3))
arr1_3 = np.full((2, 4), 7)
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[16 47 23 23 15]
 [30 43 49 45 28]]


In [ ]:
# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.
# 2.2 Extract the first row. Store it in 'row2_2'.
# 2.3 Extract the last column. Store it in 'col2_3'.
# 2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.
# 2.5 Using boolean indexing, select all elements in 'data' that are greater than 100. Store them in 'filtered_elements2_5'.

# Your code for Task 2 here:
val2_1 = data[2, 3]
row2_2 = data[0]
col2_3 = data[:, 3]
sub_arr2_4 = data[1:3, 0:2]
filtered_elements2_5 = data[data > 100]

print("Element at row 2, column 3:", val2_1)
print("First row:", row2_2)
print("Last column:", col2_3)
print("Sub-array:\n", sub_arr2_4)
print("Elements greater than 100:", filtered_elements2_5)



--- Task 2: Indexing and Slicing with Arrays ---
Element at row 2, column 3: 120
First row: [10 20 30 40]
Last column: [ 40  80 120 160]
Sub-array:
 [[ 50  60]
 [ 90 100]]
Elements greater than 100: [110 120 130 140 150 160]


In [ ]:
# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5)) # Random 4x5 array with values 1 to 20

# 3.1 Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0,
#     and elements greater than or equal to 10 remain unchanged.
# 3.2 Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.

# Your code for Task 3 here:
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("Original array:\n", arr3_1)
print("Modified array:\n", arr3_2)
print("Number of even elements:", even_count3_3)


--- Task 3: Conditional Operations ---
Original array:
 [[17 15 11 16  6]
 [14 11 18  3  5]
 [ 2  2 15 20  6]
 [17  2 14 17  7]]
Modified array:
 [[17 15 11 16  0]
 [14 11 18  0  0]
 [ 0  0 15 20  0]
 [17  0 14 17  0]]
Number of even elements: 10


In [ ]:
# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# 4.1 Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.
# 4.2 Calculate the mean of each column. Store it in 'mean_cols4_2'.
# 4.3 Find the maximum value in each row. Store it in 'max_rows4_3'.
# 4.4 Calculate the standard deviation of the entire array. Store it in 'std4_4'.

# Your code for Task 4 here:
sum4_1 = np.sum(arr4_1)
mean_cols4_2 = np.mean(arr4_1, axis=0)
max_rows4_3 = np.max(arr4_1, axis=1)
std4_4 = np.std(arr4_1)

print("Sum of all elements:", sum4_1)
print("Mean of each column:", mean_cols4_2)
print("Maximum value in each row:", max_rows4_3)
print("Standard deviation:", std4_4)


--- Task 4: Aggregation Functions ---
Sum of all elements: 84
Mean of each column: [11.          6.66666667 10.33333333]
Maximum value in each row: [12 15 20]
Standard deviation: 5.2493385826745405


In [ ]:
# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23

# 5.1 Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.
# 5.2 Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.
# 5.3 Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.
#     Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).

# Your code for Task 5 here:
reshaped_arr5_2 = arr5_1.reshape(4, 6)
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
flattened_arr5_4 = reshaped_arr5_2.ravel()
flattened_copy5 = reshaped_arr5_2.flatten()

print("Original array:\n", arr5_1)
print("4x6 Reshaped array:\n", reshaped_arr5_2)
print("2x3x4 Reshaped array:\n", reshaped_arr5_3)
print("Flattened using ravel():", flattened_arr5_4)
print("Flattened using flatten():", flattened_copy5)


--- Task 5: Reshaping and Flattening ---
Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
4x6 Reshaped array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
2x3x4 Reshaped array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Flattened using ravel(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Flattened using flatten(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.
# 6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.

# Your code for Task 6 here:
result6_1 = arr6_1 + scalar
result6_2 = arr6_1 + vector

print("After adding scalar:\n", result6_1)
print("After adding vector:\n", result6_2)



--- Task 6: Broadcasting ---
After adding scalar:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
After adding vector:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [ ]:
# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.
#     Modify the first element of 'view_arr7' to 99.
#     Observe how 'original_arr7' changes.
# 7.2 Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.
#     Modify the last element of 'copy_arr7' to 0.
#     Observe how 'original_arr7' remains unchanged.

# Your code for Task 7 here:
view_arr7 = original_arr7[:]
view_arr7[0] = 99

copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("Original array after modifying view:", original_arr7)
print("View array:", view_arr7)
print("Copy array:", copy_arr7)
print("Original array after modifying copy:", original_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
Original array after modifying view: [99  2  3  4  5]
View array: [99  2  3  4  5]
Copy array: [99  2  3  4  0]
Original array after modifying copy: [99  2  3  4  5]


In [ ]:
# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1 Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.
# 8.2 Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.
# 8.3 Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.
# 8.4 Split 'combined_arr8_3' into 3 equal parts (rows). Store them in 'part1', 'part2', 'part3'.

# Your code for Task 8 here:
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

part1, part2, part3 = np.array_split(combined_arr8_3, 3)

print("Vertical Stack:\n", vstack_arr8_1)
print("Horizontal Stack:\n", hstack_arr8_2)
print("Combined Array:\n", combined_arr8_3)
print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)


--- Task 8: Stacking and Splitting Arrays ---
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Combined Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Part 1:
 [[1 2]
 [3 4]]
Part 2:
 [[5 6]
 [7 8]]
Part 3:
 [[ 9 10]]


In [ ]:
# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1 Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.
# 9.2 Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.
# 9.3 Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)
# 9.4 Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.

# Your code for Task 9 here:
sorted_arr9_1 = np.sort(arr9_1)
sorted_cols9_2 = np.sort(arr9_2d, axis=0)
idx9_3 = np.where(arr9_1 == 9)
max_idx9_4 = np.argmax(arr9_1)

print("Sorted 1D array:", sorted_arr9_1)
print("Columns sorted independently:\n", sorted_cols9_2)
print("Index of value 9:", idx9_3)
print("Index of maximum value:", max_idx9_4)

print("\n--- Exercise Completed Successfully! ---")


--- Task 9: Sorting and Searching ---
Sorted 1D array: [1 2 3 4 5 6 7 8 9]
Columns sorted independently:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]
Index of value 9: (array([4]),)
Index of maximum value: 4

--- Exercise Completed Successfully! ---
