In [ ]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.

# Your code for Task 1 here:
s1_1 = pd.Series([10, 20, 30, 40, 50])
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("Series:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[91 80 83  5]
 [ 6 66 16  7]
 [73 74 23 87]]

DataFrame:
    A   B   C   D
0  91  80  83   5
1   6  66  16   7
2  73  74  23  87


In [ ]:
# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

# Your code for Task 2 here:
df_sales = pd.DataFrame({
    'Date': pd.date_range('2023-01-01', periods=100),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100).astype(float),
    'Quantity': np.random.randint(1, 11, 100).astype(float)
})

# Introduce NaN values
sales_nan = np.random.choice(df_sales.index, 5, replace=False)
quantity_nan = np.random.choice(df_sales.index, 3, replace=False)

df_sales.loc[sales_nan, 'Sales'] = np.nan
df_sales.loc[quantity_nan, 'Quantity'] = np.nan

print("First 10 rows of df_sales:")
print(df_sales.head(10))


--- Task 2: Synthetic Data Generation for Practice ---
First 10 rows of df_sales:
        Date Region   Product  Sales  Quantity
0 2023-01-01   East     Mouse  696.0       4.0
1 2023-01-02  South    Laptop  825.0       1.0
2 2023-01-03   West    Laptop  928.0       6.0
3 2023-01-04  North   Monitor  661.0       7.0
4 2023-01-05  South  Keyboard  754.0       7.0
5 2023-01-06   East   Monitor  661.0       1.0
6 2023-01-07   East  Keyboard  188.0      10.0
7 2023-01-08   West   Monitor  938.0       9.0
8 2023-01-09  North   Monitor  886.0       3.0
9 2023-01-10  North   Monitor  248.0       8.0


In [ ]:
# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.

# Your code for Task 3 here:
df3_1 = df_sales[['Region', 'Sales']]
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
df3_3 = df_sales[(df_sales['Region'] == 'East') &
                 (df_sales['Sales'] > 500)]
monitor_index = df_sales[df_sales['Product'] == 'Monitor'].index[0]
val3_4 = df_sales.loc[monitor_index, 'Sales']

print("Region and Sales:")
print(df3_1.head())

print("\nLaptop Records:")
print(df3_2.head())

print("\nEast Region with Sales > 500:")
print(df3_3.head())

print("\nFirst Monitor Sales:", val3_4)


--- Task 3: Indexing and Slicing in DataFrames ---
Region and Sales:
  Region  Sales
0   East  696.0
1  South  825.0
2   West  928.0
3  North  661.0
4  South  754.0

Laptop Records:
         Date Region Product  Sales  Quantity
1  2023-01-02  South  Laptop  825.0       1.0
2  2023-01-03   West  Laptop  928.0       6.0
11 2023-01-12   West  Laptop  980.0       1.0
14 2023-01-15  South  Laptop  878.0       1.0
22 2023-01-23  South  Laptop  212.0       6.0

East Region with Sales > 500:
         Date Region  Product  Sales  Quantity
0  2023-01-01   East    Mouse  696.0       4.0
5  2023-01-06   East  Monitor  661.0       1.0
16 2023-01-17   East    Mouse  694.0      10.0
18 2023-01-19   East  Monitor  773.0      10.0
19 2023-01-20   East  Monitor  846.0       9.0

First Monitor Sales: 661.0


In [ ]:
# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs).
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.

# Your code for Task 4 here:
missing_counts4_1 = df_sales.isnull().sum()
df4_2_filled = df_sales.copy()
sales_mean = df4_2_filled['Sales'].mean()
df4_2_filled['Sales'].fillna(sales_mean, inplace=True)
df4_3_dropped = df_sales.dropna()

print("Missing Values:")
print(missing_counts4_1)

print("\nSales column after filling NaN:")
print(df4_2_filled.head())

print("\nData after dropping missing rows:")
print(df4_3_dropped.head())


--- Task 4: Data Cleaning (Handling Missing Values) ---
Missing Values:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

Sales column after filling NaN:
        Date Region   Product  Sales  Quantity
0 2023-01-01   East     Mouse  696.0       4.0
1 2023-01-02  South    Laptop  825.0       1.0
2 2023-01-03   West    Laptop  928.0       6.0
3 2023-01-04  North   Monitor  661.0       7.0
4 2023-01-05  South  Keyboard  754.0       7.0

Data after dropping missing rows:
        Date Region   Product  Sales  Quantity
0 2023-01-01   East     Mouse  696.0       4.0
1 2023-01-02  South    Laptop  825.0       1.0
2 2023-01-03   West    Laptop  928.0       6.0
3 2023-01-04  North   Monitor  661.0       7.0
4 2023-01-05  South  Keyboard  754.0       7.0


/tmp/ipykernel_504/384307095.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df4_2_filled['Sales'].fillna(sales_mean, inplace=True)


In [ ]:
# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.

# Your code for Task 5 here:
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("Data with Total_Revenue:")
print(df_sales.head())

print("\nSorted Data:")
print(df5_2_sorted.head())

print("\nSales and Quantity by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

print("\n--- Exercise Completed Successfully! ---")


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---
Data with Total_Revenue:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   East     Mouse  696.0       4.0         2784.0
1 2023-01-02  South    Laptop  825.0       1.0          825.0
2 2023-01-03   West    Laptop  928.0       6.0         5568.0
3 2023-01-04  North   Monitor  661.0       7.0         4627.0
4 2023-01-05  South  Keyboard  754.0       7.0         5278.0

Sorted Data:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   East     Mouse  696.0       4.0         2784.0
1 2023-01-02  South    Laptop  825.0       1.0          825.0
2 2023-01-03   West    Laptop  928.0       6.0         5568.0
3 2023-01-04  North   Monitor  661.0       7.0         4627.0
4 2023-01-05  South  Keyboard  754.0       7.0         5278.0

Sales and Quantity by Region:
          Sales  Quantity
Region                   
East    12226.0     126.0
North   10128.0     141.0
South   16539.0   